title: Giacomo's Blog
description: >- # this means to ignore newlines until "baseurl:"
  A blog to collect the results, lessons learnt, and general thoughts about my projects and experiments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.poisonedlogs.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: giacomo270197

#theme: jekyll-shell-theme
#remote_theme: tareqdandachi/jekyll-shell-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag


sass:
  style: compressed

highlighter: rouge


header_pages:
  - home.md
  - about.md
  - blog.md
  - panda.md

font-size: large
