title: Giacomo's Blog
description: >- # this means to ignore newlines until "baseurl:"
  A blog to collect the results, lessons learnt, and general thoughts about my projects and experiments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.poisonedlogs.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: giacomo270197

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

sass:
  style: compressed

remote_theme: pages-themes/slate@v0.2.0

font-size: large

google_analytics: G-TJDJB5Z04D